bcgov/esm-server

modules/project-comments/server/models/commentperiod.model.js

This time I skipped using the original ESM-862 branch because it would've pulled a lot of unrelated changes.  This is a bug fix to the original OpenState feature.

ESM-862 bug fix order of Pending/Completed ranking was off

---

modules/core/client/scss/components/hero-banner.scss
modules/projects/client/config/project.client.routes.js
modules/projects/client/views/mine.html
modules/topics/client/views/topics-of-interest.html

- Removed the reference to 'page' in project.client.routes.js. External links should render everything at once and not filter by tab selection.
- Added filter to ng-repeat to ensure duplicate entries are not rendered (mine.html)
Additional fixes
- Fixed an issue with blurry rendering of the map thumbnail (project.client.routes.js)

MEM-317 - External Links & Resources List Changes Unexpectedly

---

modules/project-comments/client/views/public-comments/add.html

I changed the code for EPIC-868 issue by not allowing users to click submit button in add comment modal if the comment is empty and has zero docs added.

EPIC-868 Added ng-disabled for empty comments and docs

---

modules/project-comments/client/scss/project-comments.scss

Long single-string names will now truncate with the ellipsis if they run past the column width.

EPIC-964 Fixing issue with long names wrapping in the PCP list

---

modules/core/client/scss/core.scss
modules/core/server/controllers/core.dbmodel.controller.js
modules/core/server/controllers/core.routes.controller.js
modules/core/server/controllers/core.search.util.js
modules/core/server/routes/core.server.routes.js
modules/documents/client/config/documents.routes.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.info-panel.directive.js
modules/documents/client/views/docs.html
modules/documents/client/views/document-manager-info-panel.html
modules/documents/client/views/document-manager.html
modules/documents/client/views/partials/document-search-widget.html
modules/search/client/config/search.routes.js
modules/search/client/controllers/search.client.controllers.js
modules/search/client/directives/search.directive.js
modules/search/client/scss/search-results.scss
modules/search/client/scss/search-widget.scss
modules/search/client/search.client.module.js
modules/search/client/services/search.services.js
modules/search/client/views/partials/modal-search-instructions.html
modules/search/client/views/partials/search-widget.html
modules/search/client/views/search-info-panel.html
modules/search/client/views/search-results-documents.html
modules/search/client/views/search.html

Created by deleting my fork. Recreate fork.  Take a directory with all the code and remove the .git references.  Copy over the new fork.  Then carefully determine what is in and not in.

Search MVP in one commit

---

modules/search/client/views/partials/search-widget.html

Use ng-if rather than ng-show. With ng-show the spinner appears until the controller is compiled because ng-show defaults to show until it can resolve the expression. ng-if defaults to hide until it can resolve the expression.

EPIC-1032 double spinner fixed

---

modules/project-comments/client/directives/comment-directives.js

* Download CSV does not include rejected comments for EAO staff or CEAA

Fix issue EPIC-1052

---

modules/project-comments/client/services/comment.model.service.js

* Joint PCP - BUG: Download CSV headers don't match rejected documents column

Fix issue EPIC-1069

---

modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.link.directive.js
modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/views/document-manager.html
modules/projects/server/controllers/project.controller.js

Here are the git log messages for the commits pulled over, listed in the order they were applied:
[2017-04-23] [0d3fc00] Fixed folders display name not showing in folders navigation pane  {{Ushanth Loganathan}} 
[2017-04-23] [2858406] Minor indenting fixes  {{Ushanth Loganathan}} 
cherry picked the essential line of code from:
[2017-05-17] [f135cb1] EPIC-1010 - Fix link documents to VC  {{Ushanth Loganathan}} 
[2017-05-26] [400a143] EPIC-1025 - Fixed issue with move folders displayname  {{Ushanth Loganathan}} 
[2017-05-29] [c5bbb25] EPIC-1025 - Added FolderObj to move modal selectnode function  {{Ushanth Loganathan}} 
[2017-06-05] [0123efd] EPIC-1060 add copiable link to the info panel for files  {{Bryan Gilbert}}  (bgil-EPIC1060)

MEM- Pull EPIC changes that affect Doc Manager

---

modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/directives/documents.manager.rename.directive.js
modules/documents/client/views/document-manager-move.html

[2017-06-07] [3c0f91e] | EPIC-1070 - Fix folder refresh issue in move modal {{Ushanth Loganathan}} (HEAD, pull-in-epic-change)
[2017-05-11] [0a7805d] | EPIC-1001 - Changed bindings in markup for folder displayname not showing in move modal {{Ushanth Loganathan}}

MEM-354 Pull in two more changes to doc manager from EPIC

---

bower.json
config/assets/default.js
modules/core/client/app/config.js
modules/core/client/scss/global/helpers.scss
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/views/document-manager.html
modules/search/client/directives/search.directive.js
modules/search/client/views/search-results-documents.html

Copy button appears on Doc Manager and Search Results.
This PR adds clipboard.js and ngclipboard.js to the bower file. Dev's need to run bower update to get the copy to clipboard to function.

EPIC-1093 Document link layout fixed plus add Copy Link button

---

modules/documents/client/directives/documents.manager.directive.js

Refactor and clean up unused code.

EPIC-1112 sort folders and documents with natural order.

---

modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/styles/file-browser.scss
modules/documents/client/views/document-manager.html

During the migration of EPIC fixes to MEM I found a few small issues that MEM had fixed that should be on EPIC.
1. an error message said "Could ..." when it really meant "Couldn't ..." the error message only happens in unusual, difficult to reproduce, situations.
2. formatting on the Doc Manager Info Panel. 
a. aligning the labels and data
b. word wrapping long descriptions (even with content that lacks natural word breaks)
3. The tool tip on the Edit Folder icon on the ellipse menu on a folder row

EPIC-1123 small fixes

---

modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/core.scss
modules/core/client/views/dialogs/confirm.html
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/views/document-manager.html

EPIC-1117 Publish / Unpublish UI Fixes

Epic 1117 2

---

modules/project-comments/client/views/partials/period-documents-list.html

Updating to the correct column naming convention in the PCP documents interface for the 'Status' column

Fixing column sizing issue in the PCP related docs interface

---

modules/project-comments/client/scss/project-comments.scss
modules/project-comments/client/views/partials/period-documents-list.html

In the Ajax PCP the related documents layout is broken. Some rows lack the ellipse needed to download the file.
As well, the long file names are not accessible to the end user.
As well, for authenticated users, the "publish" flag is using the old circle icon. Change this to match the rest of the site.

EPIC-1157- fix PCP related docs layout issues

---

modules/recent-activity/server/models/recent-activity.model.js

Setting the default active state to false for new activities and updates. Requested specifically to address the staging of new items without concern that the initial 'save' will immediately make the new item visible.

EPIC-1113 - Setting default 'Active' State for activities to false

---

scripts/fixDocPerms/etlDocsMissingPerms.js
scripts/fixDocPerms/etlHelper.js
scripts/fixDocPerms/etlPing.js
scripts/fixDocPerms/setup.sh

ETL script to add permissions to documents that have none.
To run first invoke setup in the script directory ". ./setup.sh".
Then run "node etlDocsMissingPerms.js " to see usage instructions.

EPIC-1073 Fix missing permissions

---

modules/collections/client/directives/collections.reorder.js
modules/collections/client/scss/collections.scss
modules/collections/client/views/collection-view.html
modules/collections/client/views/collections-reorder-content.html
modules/collections/client/views/modal-collections-reorder.html
modules/core/client/scss/components/buttons.scss
modules/core/client/scss/components/drag-and-drop.scss
modules/core/client/scss/components/modal.scss
modules/core/client/scss/core.scss
modules/core/client/scss/global/mixins.scss
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.reorder.js
modules/documents/client/scss/document-manager.scss
modules/documents/client/services/documents.client.services.js
modules/documents/client/views/document-manager.html
modules/documents/client/views/partials/document-reorder-content.html
modules/documents/client/views/partials/modal-document-reorder.html
modules/documents/server/controllers/core.document.controller.js
modules/documents/server/models/document.model.js
modules/documents/server/routes/core.document.routes.js
modules/folders/client/services/folders.client.services.js
modules/folders/server/controllers/core.folder.controller.js
modules/folders/server/models/folder.model.js
modules/folders/server/routes/core.folder.routes.js

This modal dialog allows users to set the default sort order for a folder. They can say the default is sort by Name or Date (asc or desc) and they can apply this setting to all subfolders.  Or they can elect to custom sort the folder's content using drag and drop.
The drag and drop collections are disabled if the sorting option is anything but custom.
Selecting items is only enabled if custom is selected.
If any number of, say, folder objects are selected and the user clicks on a document all the folders are unselected.
If custom is selected and some items are selected these items are de-selected when the user changes the sorting option away from custom.
If the user changes the sorting option away from custom they are first given a confirmation dialog. If they select cancel they keep the …

Custom Sort Docs

---

modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/core.scss
modules/core/server/controllers/core.dbmodel.controller.js
modules/documents/client/directives/documents.manager.directive.js
modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/views/document-manager-move.html
modules/documents/server/controllers/core.document.controller.js
modules/projects/server/controllers/project.controller.js

* Add server-side logic to enforce new business rules regarding moving published content
* Fix error when trying to move files away from ROOT folder
Move dialog (client-side):
* Allow single-click to select target folder
* Provide warning when attempting to move published content into an unpublished folder

EPIC-1155 prevent moving published content into unpublished folders

---

modules/documents/client/views/document-manager-move.html

Move dialog - hide confirmation text when user is unable to move any content due to business rules

EPIC-1155 Tweaks

---

modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/core.scss
modules/documents/client/directives/documents.manager.link.directive.js
modules/documents/client/directives/documents.manager.move.directive.js
modules/documents/client/scss/document-manager-link.scss
modules/documents/client/scss/document-manager-move.scss
modules/documents/client/scss/document-manager.scss
modules/documents/client/views/docs.html
modules/documents/client/views/document-manager-link-modal.html
modules/documents/client/views/document-manager-link.html
modules/documents/client/views/document-manager-move.html
modules/documents/client/views/document-manager.html
modules/users/client/directives/dropzone.move.directive.js

Fixed issues in the Document Manager and Link Document interfaces where long file names would force functionality off the screen.
Additional Fixes
- Added ability to select text in Document Manager Interface
- Removed 'fb-browser-modal' reference from the Document Move, Document Link, and Drop Zone interfaces (these have their own encapsulated styling now).

[EPIC-1247] Fix Long File Name Issue in Document UI

---

modules/core/client/scss/components/file-browser.scss
modules/core/client/scss/global/mixins.scss
modules/documents/client/scss/document-manager-link.scss
modules/documents/client/scss/document-manager.scss
modules/documents/client/views/document-manager-link.html
modules/documents/client/views/document-manager.html
modules/search/client/scss/search-results.scss
modules/search/client/views/search-info-panel.html
modules/search/client/views/search-results-documents.html

Changes the Upload Date column to Document Date
Additional Fixes
- Ensured consistent naming conventions and spacing through affected components (column widths)
- Removed a styling selector that was preventing columns from showing at smaller device widths
- Standardized some of the information displayed for the Document Info Window and Search Result Info Window
- Added explicit labels for 'File Name', and 'File Size' in both the Documents and Documents Search Results interfaces
- Fixed an issue with incorrect selector naming convention in the Search Info Panel interface
- Added additional selector to mixins

[EPIC-1276] Change 'Uploaded Date' to 'Document Date'

---

Jenkinsfile.dev

Updated Jenkinsfile configuration: it will be used in the pipeline, to create the image that will move be pushed to *test*, move through QA and eventually be tagged to *prod*.
_dev.Jenkinsfile_ addresses a separate pipeline, used for our dev environment. The reasons to do so are:
- it is not possible (at least not right now) to specify multiple pipelines using the same Jenkinsfile.
- we want a separate pipeline for *dev*, so that changes going in to *test* and further can be selectively picked (e.g.: we want to hold something back for some reason).
While this solution is not optimal, it provides us with the possibility of managing which commits go into the Release Candidates (test environment) and are eventually tagged for production.

EM-93: Updated Jenkinsfile configuration.

---

modules/project-comments/client/directives/comment-directives.js
modules/project-comments/client/views/public-comments/add.html

- Created a flag to detect if the user is an admin (only admins can publish PCP's).
- If user is an admin, size limit is removed as well as the warning message in the dropzone.
- Also messed with the classes to ensure adequate spacing in the dropzone.

EM-321: Allow sysadmin to upload larger then 10mb filesize

---

bower.json
modules/core/server/views/layout.server.view.html

EM-692-bugfix: Revert lodash in bower.json. Remove unused conf import.

EM-692-bugfix: Revert lodash in bower.json. Remove unused conf import.

---

gruntfile.js

Enable eslint autofix for errors that can be addressed automatically (spacing, indentation, see [here](https://eslint.org/docs/rules/) for additional reference).

Enable autofix for eslint errors

---

modules/core/server/controllers/core.minio.controller.js
modules/documents/server/routes/core.document.routes.js
yarn.lock

The change should address the out-of-memory issues observed when uploading large files.
Now using disk-based multer file uploads, instead of in-memory file streaming.

Fix for big file uploads

---

modules/documents/server/routes/core.document.routes.js

I added the temp file removal to the catch clause of the running promise, so that the tempfile will be removed if the upload to Minio fails

Removed unnecessary console, handle temp file removal on failed upload.

---

modules/project-comments/client/config/commentperiod.routes.js
modules/project-comments/client/scss/project-comments.scss
modules/project-comments/client/views/period-list.html
modules/projects/client/views/project-partials/project.detail.html

EM-1251: Creating a banner that changes based on 'Open', 'Closed', an…d 'Pending' states for the period. Outside period banner on both sides will display for 7 days.
EM-1251: refactoring in progress to make code more modular
EM-1251: made pending, active, and ending banners to fit within current banner structure. TODO: Decide and if so make it so comments can be added after term only by staff.
EM-1251: added functionality for submit button appearing only for admin after period closes. Removed 'or' between buttons
EM-1251: Cleanup
EM-1251: Cleanup 1.1
EM-1251: cleanup 1.2

Pending and Closed comment banners EM-1251, EM-1252

---

modules/core/server/controllers/core.minio.controller.js
modules/documents/server/routes/core.document.routes.js
package.json
yarn.lock

DO NOT MERGE UNTIL WORK HAS BEEN CHECKED AND COMPLETED
This PR contains the changes required to add a download proxy for files stored in Minio, so that the original `/fetch` url will appear/be used in the browser instead of the Minio one.
The changes are complete and working, HOWEVER more research effort needs to be scheduled before merging them since it appears that NodeJS is having some issues handling files that are larger than 256Mb (which is the max buffer size in NodeJS). The issue is: when uploading or downloading a large file, the file transfer completes correctly, but an error resulting in the pod being restarted occurs.
The implementation uses Multer for multipart file upload, and NodeJS streams to handle the file download and proxying so it is a bit surprising that problems are …

WIP: file proxy for Minio downloads

---

modules/project-comments/client/views/period-list.html

EM-1309: made so only comment periods that have NOT opened or closed (i.e. pending) can be deleted

EM-1309: Removing the ability to delete open/closed comment periods

---

modules/utils/client/directives/utils.client.directives.js

EM-1307:
Calendar previously allowed for same day setting for start and end date as long as it followed time rules.
Changes modify the allowed days by one on each side to fit day zero rules.
i.e. Public comment period starts the day after being set. As a result pcp cannot start/end on the same day.

EM-1307: Comment period custom setting: can set same day problem

---

modules/projects/client/config/project.client.routes.js
modules/projects/client/views/project-partials/project.detail.html

EM-1354:
Added a waring popup for publishing/unpublishing a project.
Modified the JS functions behind publishing to work within promise function with 'ConfirmService' service controller.

EM-1354: Warning when un-publishing a project

---

modules/recent-activity/server/routes/recent-activity.routes.js

changed policy on api call for published pcps for a project from a logged in user to public. Needed to implement public banner functionality on eao-public. This is tied to EM-1304 work in eao-public repo.

EM-1304: Create new Public Comment Period Banners for EPIC "Public" project landing pages

---

modules/project-comments/client/views/period-list.html

EM-1424: fixed the bug that disabled deleting unpublished pcps. Current logic is: Unpublished pcps can be published or deleted. Pending can be unpublished or deleted. Open or closed cannot be deleted or unpublished.

EM-1424: Can't Delete an Unpublished, Unstarted PCP

---

modules/project-comments/client/views/period-list.html

The click event on the ellipsis button was propagating up to the pcp table row and opening the pcp page. This was a problem in Firefox and IE as well.

EM-257: Fixed ellipsis in edge

---

modules/documents/server/routes/core.document.routes.js

Append file extension at download time based on the `internalExt` field which seems to stay intact in the database, even when the filename loses its extension.

EM-302 Fix missing file extensions on download
