modules/project-comments/server/models/commentperiod.model.js
Reverts bcgov/esm-server#6
This breaks esm-dev.
=> Revert "ESM-862 bug fix order of Pending/Completed ranking was off"

modules/communications/client/views/communication-list.html, modules/communications/client/views/recipients-manager.html, modules/core/client/scss/components/ng-table-overrides.scss, modules/core/client/scss/components/table.scss, modules/core/client/scss/core.scss, modules/core/server/views/layout.server.view.html, modules/email-templates/client/views/email-template-list.html, modules/groups/client/views/group-edit.html, modules/groups/client/views/group-list.html, modules/groups/client/views/group-view.html, modules/invitations/client/views/invitation-list.html, modules/organizations/client/views/org-edit.html, modules/organizations/client/views/org-entry.html, modules/organizations/client/views/organization-edit.html, modules/organizations/client/views/organization-list.html, modules/organizations/client/views/organization-view.html, modules/project-comments/client/views/period-list.html, modules/project-conditions/client/views/projectcondition-list.html, modules/topics/client/views/topic-list.html, modules/users/client/views/admin/user-list.html, modules/vcs/client/views/vc-list.html
- Updated styling for Organization UI
- Moving updated styling / markup for new table styling over.
=> ESM-855 - Organization Management UI

config/lib/seed.js, config/seed-data/defaults.js, config/seed-data/folders.js, modules/core/server/controllers/core.helpers.controller.js, modules/core/server/controllers/core.routes.controller.js, modules/documents/client/directives/documents.manager.directive.js, modules/documents/client/views/document-manager.html, modules/folders/server/controllers/core.folder.controller.js, modules/folders/server/models/folder.model.js, modules/folders/server/routes/core.folder.routes.js, modules/projects/client/services/project.model.service.js, modules/projects/server/controllers/project.controller.js, modules/projects/server/routes/project.routes.js, scripts/migrateFolders.js
This reworks the folder structure, ui and logic around management of folders.  It requires a DBFIX after deploying.
=> Landing new folder structure logic.

config/lib/seed.js, config/seed-data/defaults.js, config/seed-data/folders.js, modules/core/server/controllers/core.helpers.controller.js, modules/core/server/controllers/core.routes.controller.js, modules/documents/client/directives/documents.manager.directive.js, modules/documents/client/views/document-manager.html, modules/folders/server/controllers/core.folder.controller.js, modules/folders/server/models/folder.model.js, modules/folders/server/routes/core.folder.routes.js, modules/projects/client/services/project.model.service.js, modules/projects/server/controllers/project.controller.js, modules/projects/server/routes/project.routes.js, scripts/migrateFolders.js
Reverts PR #21, which itself was a reversal of PR #20 in order to land hotfix PR #22.
=> Re-Apply original PR #20

modules/communications/client/directives/recipients.directive.js
Throwing error causing page not to render.
=> Remove codelists - was throwing an error on the recipient page

config/lib/seed.js, config/seed-data/defaults.js, config/seed-data/folders.js, modules/core/server/controllers/core.helpers.controller.js, modules/core/server/controllers/core.routes.controller.js, modules/documents/client/directives/documents.manager.directive.js, modules/documents/client/views/document-manager.html, modules/folders/server/controllers/core.folder.controller.js, modules/folders/server/models/folder.model.js, modules/folders/server/routes/core.folder.routes.js, modules/projects/client/services/project.model.service.js, modules/projects/server/controllers/project.controller.js, modules/projects/server/routes/project.routes.js, scripts/migrateFolders.js
=> Apply original PR #20

modules/projects/client/views/project-partials/project.entry.html
- Cleaning up the spacing / button positioning on the 'Edit Project > Contacts' interface
=> Edit Project UI Fix

modules/documents/client/directives/documents.manager.directive.js, modules/documents/client/views/document-manager.html, modules/folders/client/folders.client.module.js, modules/folders/client/services/folders.client.services.js, modules/folders/server/controllers/core.folder.controller.js, modules/folders/server/routes/core.folder.routes.js
Migrating this functionality into MEM
=> EPIC-843: Adding in permissions feature to folders.

modules/users/client/views/user-entry.html
- See modules/users/client/views/user-entry.html
=> EPIC-856-fix - Fixing binding property for 'Group Names'

config/lib/seed.js, config/seed-data/codelist-data.js, modules/documents/client/directives/documents.manager.edit.directive.js, modules/documents/server/controllers/core.document.controller.js
Document Type pick values should be as follows and should be in Alpha Sort order.
* Amendment
* Assessment
* Certificate
* Comments/Submissions
* Correspondence
* Inspection Report
* Letter
* Notice/News Release
* Notification
* Order
* Project Information
* Report/Plan
* Request
*NOTE:* - Certificate Amendment becomes Amendment
=> EPIC-927	Document Type Values

modules/documents/server/models/document.model.js, modules/search/client/directives/search.directive.js, modules/search/client/views/search-results-documents.html
Search MVP. Remove creation of unused FTS index. Fix pagination controls. Fix NPE on deselection of row (info panel)
=> Search MVP PR onto develop - small fixes

config/assets/default.js, config/assets/production.js, modules/core/client/app/config.js, modules/core/server/views/copy-layout.html
=> Revert "Removing sanitize module for now and injection of module we are not u…"

modules/home/client/views/home.html
Quick change for the values in the mining production value fast fact
=> Updating fast facts content

modules/documents/client/views/document-manager-link.html, modules/documents/client/views/document-manager-move.html, modules/documents/client/views/document-manager.html
Updated the HDD icon to the HOME icon for document browser interfaces
=> MEM-349 - Document UI [root icon] - move from EPIC

modules/core/client/scss/components/tab-nav.scss
- Fixed the usability (color) issue with the navigation tabs on the project pages.
- Changed color references to mixins
- Added Hover state
=> MEM-350 - Font Color Change

modules/project-comments/client/directives/comment-directives.js
* Attachment icon not showing on PCP comment display page for public users
=> Fixes issue EPIC-1016

modules/documents/client/directives/documents.dropzone.upload.directive.js, modules/documents/client/services/documents.client.services.js, modules/documents/client/services/documents.upload.service.js, modules/documents/client/views/document-dropzone-upload-modal.html, modules/documents/client/views/document-dropzone-upload.html, modules/documents/server/controllers/core.document.controller.js, modules/documents/server/routes/core.document.routes.js, modules/users/client/config/users.client.routes.js, modules/users/client/directives/dropzone.move.directive.js, modules/users/client/scss/user-entry.scss, modules/users/client/views/user-partials/dropzone-move.html, modules/users/client/views/user-partials/user-activities-orig.html, modules/users/client/views/user-partials/user-activities.html
This feature is essentially complete with two exceptions.  EPIC-1019 and 1029.
Also this PR will have a conflict on whitespace in core.document.routes.js.  I tried several times to prevent this conflict without success. It's just whitespace so manual merge is easy.
=> Proponent self reporting - WIP

modules/core/client/views/header.client.view.html, modules/project-comments/client/views/period-edit.html, modules/utils/client/controllers/utils.client.controllers.js, modules/utils/client/directives/utils.client.directives.js, modules/utils/client/views/partials/modal-date-picker.html, modules/utils/client/views/partials/modal-day-calculator.html
Restore reverted code. Added Easter Monday and Boxing Day detection. Added error messages for start > end dates. Counts stats. Adjusted day zero logic. Added day zero rules link. Moved Day Calculator to TOOLS menu.
MVP: Calculator is still in modal. Will need to be in separate window one day.
=> EPIC-929 Day Calculator MVP candidate

modules/documents/server/controllers/core.document.controller.js, modules/users/client/controllers/authentication.client.controller.js
Adding in proponent can upload files. 
Authenticated user goes to dashboard.
=> Proponent self reporting

modules/documents/client/views/partials/modal-document-instructions.html, modules/search/client/directives/search.directive.js, modules/search/client/views/partials/search-widget.html
Based on comments from sprint review:
Show search instructions on doc page.
Show spinner on docs page when user launches search.
=> EPIC-1033 and 1032

modules/core/client/scss/components/file-browser.scss, modules/documents/client/views/document-manager.html, modules/search/client/scss/search-results.scss, modules/search/client/views/search-results-documents.html
Fixed incorrect padding on the no-results row
Fixed an issue where the info button would appear over top the 'close' button
Small styling tweaks for the drill-in/out buttons
=> UI Clean-up

modules/documents/client/directives/documents.dropzone.upload.directive.js, modules/documents/client/views/document-dropzone-upload-modal.html, modules/documents/server/controllers/core.document.controller.js, modules/documents/server/routes/core.document.routes.js, modules/projects/server/controllers/project.controller.js, modules/users/client/config/users.client.routes.js, modules/users/client/directives/dropzone.move.directive.js, modules/users/client/scss/user-entry.scss, modules/users/client/views/user-partials/dropzone-move.html, modules/users/client/views/user-partials/user-activities.html
PSR is almost ready for a PR to master. Just want to validate it works in IE, mobile and get advice on layout changes. UI layout tweaks are required.
=> Proponent self reporting system. WIP

config/lib/seed.js, config/seed-data/codelist-data.js, modules/codelists/client/config/codelists.routes.js, modules/codelists/client/services/codelist.services.js, modules/codelists/client/views/codelist-list.html, modules/core/client/app/constants.js, modules/projects/client/controllers/project.client.controllers.js, modules/projects/client/directives/project.client.directives.js, modules/projects/client/views/project-partials/project-tombstone.html, modules/projects/client/views/project-partials/project.entry.html
Fix codelist refresh, busy spinner and pagination
=> EPIC-990 Change CEAA constants to Field Management (codelists)

scripts/ETL-ceaa-to-projects.js
ETL script to push ceaa role into defaults (for new projects) and roles for projects (to add role to user of existing project).
=> EPIC-1014 ETL to add CEAA roles

modules/core/client/scss/core.scss, modules/documents/client/directives/documents.dropzone.upload.directive.js, modules/documents/client/services/documents.upload.service.js, modules/documents/client/views/document-dropzone-upload-modal.html, modules/documents/client/views/document-dropzone-upload.html, modules/documents/server/controllers/core.document.controller.js, modules/documents/server/routes/core.document.routes.js, modules/projects/server/controllers/project.controller.js, modules/users/client/config/users.client.routes.js, modules/users/client/directives/dropzone.move.directive.js, modules/users/client/scss/user-dashboard.scss, modules/users/client/views/user-partials/dropzone-move.html, modules/users/client/views/user-partials/user-activities.html
Rework the Dashboard (/activities) to allow proponents to drop files into the system and for assessment team members to review and move the files into project.
User roles that can move files includes: "project-system-admin", "assessment-admin", "assessment-lead", "assessment-team" and "project-epd"
User roles that can upload files includes: "project-system-admin", "proponent-lead", "proponent-team"
=> Proponent self reporting system. 

modules/core/server/controllers/core.dbmodel.controller.js
Quick fix to the sanitize code that removed user passwords and salts. Without this fix users can not add new directories to projects.
=> Hot Fix. Can't add directories to any project

modules/documents/client/directives/documents.manager.move.directive.js
@marklise I made the modification to the code and now we can add and move folders inside the move modal. Please let me know if the code needs further changes.
=> EPIC-1074 - Fix Document Management: [folder not appearing after add in]

modules/documents/client/directives/documents.manager.directive.js
Refactor and clean up unused code.
=> EPIC-1112 - change sort order for display name to natural order.

modules/core/client/services/core.movable.modal.service.js, modules/utils/client/directives/utils.client.directives.js, modules/utils/client/views/partials/modal-day-calculator.html
Implemented solution can easily be added to other dialogs.
=> EPIC-1080 Day calculator dialog can be moved. 

modules/documents/client/directives/documents.manager.directive.js
Reverts bcgov/esm-server#177
Breaks folder display.
=> Revert "EPIC-1112 - change sort order for display name to natural order."

modules/core/client/views/dialogs/confirm.html, modules/documents/client/directives/documents.manager.directive.js
Added warning alert to confirmation dialog
=> EPIC-1117 - User Interface fixes

modules/project-comments/client/directives/comment-directives.js, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/public-comments/detail.html
EPIC-1105 can not publish empty comment, EAO PCP buttons match color of Joint PCP
EPIC-1104 can not publish comment until all attachments are rejected or published
=> EPIC-1104, 1105 PCP comment vetting

modules/core/client/services/core.model.service.js, modules/core/server/controllers/core.routes.controller.js, modules/projects/server/routes/project.routes.js
* Open up the "query" endpoint to public users. It is currently restricted to authenticated users.
* Add support for specifying which fields to return in server response for API query endpoints
=> EPIC-1054 ArcGIS - Auto-generate GeoJSON from EPIC data

modules/core/client/scss/components/file-browser.scss, modules/core/client/services/core.dialog.service.js, modules/documents/client/directives/documents.dropzone.upload.directive.js, modules/documents/client/directives/documents.manager.upload.directive.js, modules/documents/client/views/document-dropzone-upload.html, modules/documents/client/views/document-manager-upload.html, modules/project-comments/client/directives/comment-directives.js, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/joint-public-comments/partials/pkg-1.html, modules/project-comments/client/views/joint-public-comments/partials/pkg-2.html, modules/project-comments/client/views/public-comments/add.html
Prevent accidental drop of files anywhere but the target dropzone. (Ideally would make the whole application area a drop target but we are using a module that does not allow for this.)
=> EPIC-799 Drag and drop on background bug

modules/core/client/fn-filename/README.md, modules/core/client/fn-filename/index.js, modules/documents/client/directives/documents.manager.edit.directive.js, modules/documents/client/views/document-manager-edit.html, modules/documents/client/views/document-manager.html
Document filename is used for download. Allow edit and display of filename for authenticated users. Add filename validation component.  EPIC does not need ETL.
=> EPIC-1136 Document filename 

modules/core/client/config/core.client.menus.js, modules/core/client/scss/core.scss, modules/recent-activity/client/scss/recent-activity.scss, modules/recent-activity/client/views/recent-activity-edit.html, modules/recent-activity/client/views/recent-activity-list.html
- Updated the navigation title to reflect naming changes
- Removed news styling from core style sheet and placed in appropriate module (recent activity)
- Interface clean-up on the recent activity list and edit views
=> EPIC-1113 - UI Updates / Cleanup for Recent Activities Views

modules/recent-activity/client/config/recent-activity.routes.js, modules/recent-activity/client/views/recent-activity-list.html
=> EPIC-1113 - Adding busy flag for recent activites

modules/documents/server/routes/core.document.routes.js
When downloading or fetching a file make sure the filename has a file extension. Many files in the system don't have the extension.  The download file name is the documentFileName or (if empty) the displayName of (if empty) the internal name.
We may choose to also compose and run an ETL that resets the file extension on all filename properties.  This is optional.
=> EPIC-1166 files lack extension

modules/documents/client/directives/documents.manager.edit.directive.js
=> [Dev] Folder rework - 3

modules/documents/client/directives/documents.manager.edit.directive.js, modules/documents/client/directives/documents.manager.rename.directive.js, modules/projects/server/controllers/project.controller.js
Prevent duplicate names in same parent folder.
=> MEM-464 fix folder renaming. 

modules/documents/client/directives/documents.manager.edit.directive.js, modules/documents/client/directives/documents.manager.rename.directive.js, modules/projects/server/controllers/project.controller.js
=> Revert "MEM-464 fix folder renaming. "

modules/collections/client/scss/collections.scss, modules/collections/client/views/collection-edit.html, modules/collections/client/views/collection-view.html, modules/collections/client/views/collections-list.html, modules/core/client/scss/components/forms.scss, modules/core/client/scss/core.scss
Refactor / clean-up of the collections interface(s) and styling
Additional fixes
- Removed the majority of the form element styling out of core.scss into forms.scss
- Added status column to both main and other document components
- Fixed incorrect usage of title tag properties on various elements
- Fixed an issue where the side navigation project link would not render it's with on initial load.
=> MEM-486 Collection UI Fixes

package.json
* Add `npm run build` task to `package.json`
=> Fix global GIT configuration in `package.json`

modules/core/server/controllers/core.dbmodel.controller.js, modules/search/server/routes/search.routes.js
Temporary: Some debug code in there to facilitate debugging on dev server.
=> MEM-465: Search API changes.

modules/core/client/scss/components/file-browser.scss
=> EPIC-1210 - Fixing checkbox column styling issue

modules/core/client/scss/core.scss, modules/core/client/scss/global/footer.scss, modules/core/client/scss/global/header.scss, modules/core/client/scss/global/layout.scss, modules/core/client/scss/global/sidenav.scss, modules/core/client/views/footer.client.view.html, modules/core/client/views/menu.client.view.html, modules/core/client/views/role-users-modal.html
- Removed side navigation from core and moved into it's own component style sheet
- Footer markup/styling clean-up (bringing more in-line with newer development)
- Fixed an issued with hover/focus states on main navigation items in larger devices (desktop)
- Fixed an issue with the project side navigation inner container not sizing correctly
=> EPIC-1227 - Misc Fixes / Clean-up

modules/core/client/scss/global/header.scss, modules/core/client/views/footer.client.view.html, modules/core/client/views/header.client.view.html
Removed the navigation items pointing to ESM-MASTER. See notes below
- Dashboard remains as My Projects
- Calculator remains as a top-level navigation component
- Home, Contact and Guidance navigate to appropriate pages
- Small styling fix to ensure user information is case-sensitive (unique)
=> EPIC-1227 - Removing Navigation Items

modules/core/client/scss/components/misc.scss, modules/projects/client/views/projects.abstract.html
Fixed an issue where the intro modal was preventing users from dismissing it on small devices.
=> [EPIC-1270] Intro Modal Bug Fix

modules/core/client/scss/components/forms.scss, modules/core/client/scss/components/misc.scss, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/joint-public-comments/period-edit.html, modules/project-comments/client/views/partials/period-documents-list.html, modules/project-comments/client/views/public-comments/period-edit.html
- Fixed issues with long names in the Related Documents interface
- General clean-up
- Added some missing selectors back into misc.scss
=> [EPIC-1271] Fixing Styling/Layout Issues in PCP Module

modules/projects/server/routes/project.routes.js
- added stripped-down projects picklist API
=> MEM-594 Relate MEM mines to EPIC projects: /api/projects/picklist/ext

modules/core/client/views/footer.client.view.html, modules/core/client/views/header.client.view.html
Updating Navigation items for public launch.
=> Updating navigation to reflect public site

package.json
updates to:
- node
- npm
- acl
- async
- body-parser
- bower
=> EPIC-1293 Slow rollout of changes part 1

config/lib/express.js, package.json
other dev dependencies and multer.
=> EPIC-1293 Slow rollout of changes part 6: dev dependencies

modules/project-comments/client/views/joint-public-comments/partials/how-it-works.html, modules/project-comments/client/views/public-comments/add.html
The privacy policy has to be updated at eao.gov.bc.ca
=> Remove Rumon's name from pop up on submit a public comment

modules/project-comments/client/config/commentperiod.routes.js
=> EM-98 Removed temporary PCP redirects to legacy site.

modules/core/client/app/init.js
Added event handler to cancel/close modal windows when navigating away from the current page.
=> EM-41: Close modals when navigating away from the current page.

modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/period-list.html
> The number of comments icon on a public comment period is misleading to internal users
- Replaced "Comments" header with "Published Comments"
- Modified formatting for mobile view of the same window, as detailed in Jira ticket
- Formatted whitespace for both involved files
=> EM-146 fix

modules/documents/client/directives/documents.manager.add.directive.js, modules/documents/client/directives/documents.manager.edit.directive.js, modules/documents/client/directives/documents.manager.rename.directive.js, modules/documents/client/views/document-manager-edit.html
> Document manager naming does not account for case sensitivity
- Altered add and batch-rename functionality to account for case sensitivity
- Refactored in-line edit property to use new modal in-line alert protocol, altered functionality to account for case-sensitivity
- Fixed whitespace for involved files, homogenized code format between esm-server and mem-admin
=> EM-288 fix for EPIC

modules/projects/server/controllers/project.controller.js
> Edit Project - Provide Details on Last User to Modify a Project
This data is now exposed for use in the view, using the call {{ project.updatedBy.displayName }}. For security concerns, no other data has been exposed on the modifying user.
=> EM-144 backend data exposure

modules/project-comments/client/services/comment.model.service.js, sonar-runner/build.gradle
@RandyInVictoria
The file change is, yet again, a non UTF-8 file for which I changed the encoding (not sure how it got there, but SonarQube was flagging it).
=> Updated SonarQube configuration to use better build names.

modules/core/client/app/init.js, modules/project-comments/client/directives/comment-directives.js, modules/vcs/client/controllers/vc.controller.js, modules/vcs/client/views/vc-list.html
Clicking on the pagination at the bottom of the page now scrolls the user back to the top of the window.
=> em-177 clicking pagination scrolls to the top

modules/projects/server/controllers/project.controller.js, modules/projects/server/routes/project.routes.js
=> em-443 added type property for recent activity

config/assets/default.js, config/assets/production.js, modules/core/client/app/init.js, modules/recent-activity/client/views/recent-activity-edit.html
Added the following options to the text area:
- Bold, italics
- Alignment
- Linking
- Ordered and unordered lists
- Indentation
=> em-187 added tinymce options to textarea

modules/projects/server/controllers/project.controller.js, modules/projects/server/models/project.model.js, scripts/projectDataUpdate/certDate.csv, scripts/projectDataUpdate/package.json, scripts/projectDataUpdate/projectDataUpdate.js
> Method to input historical EA Decision data and method to input future dates
- Created data field and exposed data to controller server-side
- Added script to populate data field via direct database interfacing, included .csv containing public data to be loaded
=> EM-352: Script for population, backend data exposure

modules/projects/server/controllers/project.controller.js
Added eacDecision to public project query
=> em-443 added eacDecision to query

modules/core/client/app/init.js, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/period-view.html
Verified in ie, chrome, and ff:
- IE doesn't support element.scrollTo, only window.scrollTo so changed any element.scrollTo to element.scrollTop = 0
- Styling was messed up, fixed flexbox stuff with Jeremy
=> em-177 fixed ie bugs

modules/projects/client/controllers/project.client.controllers.js, modules/projects/client/views/project-partials/project.entry.html
> Create field for EA Certificate Decision Date in Edit Project menu
- Administrative users can now use a date-picker in the Edit Project menu to add an EA Certification Decision Date. The date may also be cleared, which sets the decisionDate value to null in the model.
=> EM-524: Date picker added to Edit Project

config/seed-data/defaults.js
- Removed all default roles from the requested features in exception of the project system administrator
- Added comments to provide clarity to each section
=> [EM-320] Fix default seed to restrict views to project system admin only

Jenkinsfile.dev, zap/README.md, zap/runzap.sh
Changes include:
- adding the BDDStack step to have SonarQube scans every time a change is pushed to Dev.
- minor tweaks to the Jenkinsfile: there apparently aren't conventions on how to structure the Jenkinsfile, I simplified a bit the Dev pipeline in order to make it more straightforward (no need to have arrays of variables if there only is one option).
=> EM-93: Updated Jenkinsfile.dev to include Sonarqube scan for project.

modules/projects/server/controllers/project.controller.js
If at different depths of folder directory, able to add duplicate name.
For example:
ROOT > A1 > A1
=> em-172 allow duplicate names at different depths of tree

modules/projects/client/controllers/project.client.controllers.js, modules/projects/client/views/project-partials/project.entry.html
- Show decision date in date picker when editing a project's details
- Changed placeholder to what other date pickers have (YYYY-MM-DD)
=> em-664 show decision date when editing project

modules/users/client/config/users.client.routes.js, modules/users/client/views/user-partials/user-activities.html
- Reinstated sorting for the table in 'My Projects'
=> EM-306 Reinstated sorting for the table in 'My Projects'

modules/core/client/directives/menu.client.directives.js, modules/core/client/views/menu.client.view.html
Side NavBar item is now highlighted when user navigates to it.
=> em-114 make active tab highlighted in side nav bar

Jenkinsfile, Jenkinsfile.dev
Fixed a silly syntax error that sneaked in.
=> EM-93: Fixed misplaced bracket in jenkinsfile.

modules/core/client/directives/menu.client.directives.js
Missed changing a variable name from location to locationParts
=> em-114 fixed side menu highlighting

functional-tests/src/test/groovy/pages/app/MyProjectsPage.groovy, functional-tests/src/test/resources/GebConfig.groovy
Functional Tests - Fix test due to changed selector.
=> Functional Tests - Fix test due to changed selector.

modules/core/client/scss/components/context-menu.scss, modules/core/client/scss/components/file-browser.scss, modules/core/client/scss/core.scss, modules/core/client/scss/themes/default.scss, modules/documents/client/views/document-manager.html, modules/search/client/views/search-results-documents.html
Changed dropdown menus in document manager to context menus by using ui-bootstrap's popover directive.
=> em-115 changed dropdown menu to context menu

modules/projects/client/controllers/project.client.controllers.js
Changed from using lodash to normal javascript check for empty decisionDate field
=> em-443 fixed decision date not displaying error on load error

modules/core/client/scss/global/helpers.scss, modules/documents/client/views/document-manager.html, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/partials/period-documents-list.html, modules/project-comments/client/views/period-list.html, modules/project-comments/client/views/public-comments/list.html, modules/project-comments/client/views/public-comments/main.html, modules/project-comments/client/views/public-comments/period-edit.html
Adding new comment periods will no longer provide the option to go between the standard and joint comment period types.
Additional Fixes 
- Updated all context menus in the PCP interfaces to new pattern
- Fixed an issue where the spacing on the comment list
- Fixed an issue with the date picker rendering on the edit screen
=> [EM-311] Remove EAO/CEE Public Comment Period Functionality

scripts/recentActivitiesDataUpdate/package.json, scripts/recentActivitiesDataUpdate/projectDataUpdate.js
Updates documentUrl and contentUrl such that if the hostname was https://projects.eao.gov.bc.ca, it removed the hostname.
If the hostname was not the prod esm-server, it keeps the entire url the same.
=> em-820 created script to update recentactivities data

modules/documents/client/views/document-manager-upload-modal.html, modules/documents/client/views/document-manager-upload.html, modules/documents/client/views/document-manager.html, modules/project-comments/client/views/public-comments/add.html
- Fixed document upload modal not properly checking the upload service's fileList for content. This was causing no files to appear in the upload target list
- Fixed context menu for document manager in-line publishing/unpublishing.
- Fixed small typo in Public Comment Period (.pdf's are allowed for public upload)
=> EM-303B: Several small changes in document manager

modules/project-comments/client/directives/comment-directives.js
=> EM-798: Add 'other' to comment rejection reasons

modules/documents/client/directives/documents.manager.directive.js, modules/documents/client/views/document-manager.html
Also fixed a small typo in the context menu: Rename -> Edit for files.
=> EM-797: Date Sort to use Document Date

.gitignore, Jenkinsfile.dev, config/env/functional.js, functional-tests/src/test/groovy/fixtures/FixtureManager.groovy, functional-tests/src/test/groovy/fixtures/data/adminUser.json, gruntfile.js
Please note FT in pipeline cannot be enabled until the OpenShift image for BDDStack testing is stable.
=> EM-786: Enable FT in pipeline

modules/projects/server/controllers/project.controller.js, modules/projects/server/routes/project.routes.js, modules/recent-activity/server/controllers/recent-activity.controller.js, modules/recent-activity/server/routes/recent-activity.routes.js
This change is required for *eao-public* to retrieve project details and related news in a two-step process, rather than everything at once.
=> EM-910: Split retrieval of recent activities for a project into its own route.

modules/recent-activity/server/controllers/recent-activity.controller.js
Fixed query used  by recent activities API.
=> EM-910-fix: Fixed query for retrieving recent activities by project.

modules/users/server/controllers/users/users.authentication.server.controller.js
Had to revert this change since the logout request is not being populated the way I was expecting.
=> EM-1000: Reverted changes to logout logic.

modules/core/client/app/constants.js, modules/projects/client/views/project-partials/project-tombstone.html, modules/projects/client/views/project-partials/project.entry.html
=> WIP - EM-1026: added "not designated reviewable" to drop down box

modules/project-comments/client/services/comment.model.service.js, modules/recent-activity/client/config/recent-activity.routes.js, modules/recent-activity/server/controllers/recent-activity.controller.js, modules/recent-activity/server/routes/recent-activity.routes.js
Commit 1: Added missing header.
Commit 2: Realized we actually want to remove this header and its data, so did that.
Commit 3: Formatting some unrelated files.
=> EM-1084: Add missing data to match column header

modules/projects/client/config/project.client.routes.js, modules/projects/client/views/project-partials/project.detail.html
Turns out all of the functionality was already there from before, including an "unPublish" permission.
So I just added the html button, and the one controller function to call the api.
=> EM-1031: Add 'unpublish project' button to project page

modules/collections/client/config/collections.routes.js, modules/collections/client/views/collection-edit.html, modules/documents/client/views/document-manager-edit.html, modules/project-comments/client/config/commentperiod.routes.js, modules/project-comments/client/directives/comment-directives.js, modules/project-comments/client/views/public-comments/open-house-edit.html, modules/project-comments/client/views/public-comments/period-edit.html, modules/projects/client/config/project.client.routes.js, modules/projects/client/views/project-partials/project.entry.html, modules/projects/client/views/project-partials/project.schedule.html, modules/projects/client/views/project-partials/project.schedule.milestone.add.modal.html, modules/projects/client/views/project-partials/project.schedule.milestone.edit.modal.html, modules/recent-activity/client/config/recent-activity.routes.js, modules/recent-activity/client/views/recent-activity-edit.html, modules/utils/client/controllers/utils.client.controllers.js, modules/utils/client/views/partials/modal-day-calculator.html
EM-292: edit milestone datepicker working
EM-292: edit phase half working
EM-292: day calculator date pickers working
EM-292: recent activity date picker working
EM-292: comment period date picker working
EM-292: open house date picker working
EM-292:  edit phase date picker works no validation, put back disables in comment period
EM-292: passed moment into recent-activity.routes functions
EM-292:  edit phase date picker works
EM-292: added error messages to some of the datepickers
EM-292: added user input for datepickers and made them dropdown
=> EM-292: added user input for datepickers and made them all dropdown

modules/core/client/scss/components/forms.scss, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/views/public-comments/detail.html, modules/project-comments/server/models/comment.model.js, modules/recent-activity/client/config/recent-activity.routes.js, modules/recent-activity/server/controllers/recent-activity.controller.js, modules/recent-activity/server/routes/recent-activity.routes.js
Initial development for the proponent response interface.
=> [EM-1050] Proponent Response Prototype

modules/projects/client/views/project-partials/project.detail.html
Updated the publish/unpublish buttons to conform to established patterns.
=> [UX-Fix] Fixed Publish/Unpublish Components in Project Interface

modules/core/client/directives/core.client.directives.js, modules/core/client/views/export-modal.html, yarn.lock
Added better support for all Browsers (ie is the worst).
The code was borrowed from another directive that has a csv download.
Its a bit ugly, but apparently between angular1 and ie, there isn't much of a better way to support all browsers.
=> EM-88-ieFix: better browser support

modules/core/client/scss/components/forms.scss, modules/project-comments/client/directives/comment-directives.js, modules/project-comments/client/scss/project-comments.scss, modules/project-comments/client/services/comment.model.service.js, modules/project-comments/client/views/public-comments/detail.html, modules/project-comments/client/views/public-comments/list.html, modules/project-comments/server/controllers/comment.controller.js, modules/project-comments/server/models/comment.model.js, modules/project-comments/server/routes/comment.routes.js
EM-1050: Proponent Response Prototype
EM-1052: Added proponent response filter to comments table
EM-1096: Update api to remove proponent response as needed. Update api permissions to only return published comments
Code Review already performed against individual tickets.
=> Proponent Response Feature

config/seed-data/defaults.js, modules/documents/server/routes/core.document.routes.js, modules/users/client/services/users.client.service.js, scripts/updateRolesAndPermissions/updateRolesAndPermissions.js
There are no real code changes.  Some files are just formatting, and in defaults.js, I updated it to match what the _defaults table in mongo WILL look like once the update script is executed.
=> EM-1118: Update project-team role to allow more document manager privs.

modules/project-comments/client/config/commentperiod.routes.js, modules/project-comments/client/views/public-comments/period-edit.html, modules/utils/client/controllers/utils.client.controllers.js, modules/utils/client/views/partials/modal-date-picker.html
EM-1199: dates saved with no time will default to 9AM to 4PM 
EM-1199: date ranges work with default time but custom range time needs to be set
=> EM-1199: time picker for comment period start/end

modules/project-comments/client/views/public-comments/period-edit.html
EM-1308: new link to day calculator beside date form groups
=> EM-1308: Create a button link to day calculator close to calendar controls

modules/core/client/app/init.js
EM-1337: updated version number for google maps support
=> EM-1337: Update Google Map keys in EPIC

README.md
=> HOTFIX: eguide readme update

modules/documents/client/views/document-manager.html
fixed safari ellipsis menu item not firing on click
=> EM-1415: ellipsis click failing on safari

Jenkinsfile.dev
This may not work for esm-server, it was problematic before but we will try with the new image
=> ESM-1341: Update bddstack image, try re-enabling bdd block

config/lib/express.js
Changed the express-session `resave` option to false. This shouldn't cause any problem but lets keep an eye out.
=> EM-185 (Users not logged out correctly on some pages)

modules/documents/client/controllers/documents.client.controllers.js, modules/documents/client/views/document-manager.html, modules/documents/server/routes/core.document.routes.js
=> Undo the changes made today to avoid polluting test.

modules/documents/client/directives/documents.manager.directive.js
remove some broken changes from dev before they hit test.
=> Revert changes

modules/project-comments/client/views/partials/period-documents-list.html
This is just a followup application of the solution in EM-266, missed a spot.
=> EM-296 open attached documents inline

package.json
addresses security issue brought to attention in rocketchat.
=> EM-332 package upgrade
